// ─── Tutoring Data ───────────────────────────────────────────────────────────
// All content from tutoring materials — Palestinian dialect

export interface TutoringItem {
  arabic: string;
  transliteration: string;
  english: string;
  note?: string;
}

export interface TutoringLesson {
  id: string;
  title: string;
  emoji: string;
  description: string;
  color: string;
  items: TutoringItem[];
  rules?: string[];
}

export const tutoringLessons: TutoringLesson[] = [
  // ─── Days of the Week ────────────────────────────────────────────────────
  {
    id: "days",
    title: "Days of the Week",
    emoji: "📅",
    description: "Days, time nouns, and calendar vocabulary in Palestinian dialect",
    color: "#2563EB",
    rules: [
      "Days end in -ين (yeen) for most days",
      "اليوم (il-yōm) = today | إمبارح (imbāriḥ) = yesterday | بكرا (bukra) = tomorrow",
      "الأسبوع (il-isbūʿ) = the week | الشهر (ish-shahar) = the month",
    ],
    items: [
      { arabic: "الأحد",      transliteration: "il-Aḥad",      english: "Sunday",     note: "1st day of week in Arabic calendar" },
      { arabic: "الاثنين",    transliteration: "il-Ithnayn",   english: "Monday" },
      { arabic: "الثلاثاء",   transliteration: "ith-Thalātha", english: "Tuesday" },
      { arabic: "الأربعاء",   transliteration: "il-Arbaʿa",   english: "Wednesday" },
      { arabic: "الخميس",     transliteration: "il-Khamīs",   english: "Thursday" },
      { arabic: "الجمعة",     transliteration: "il-Jem'a",    english: "Friday",     note: "Jumu'ah — day of prayer" },
      { arabic: "السبت",      transliteration: "is-Sabt",     english: "Saturday" },
      { arabic: "اليوم",      transliteration: "il-yōm",      english: "Today" },
      { arabic: "إمبارح",     transliteration: "imbāriḥ",     english: "Yesterday" },
      { arabic: "بكرا",       transliteration: "bukra",        english: "Tomorrow" },
      { arabic: "بعد بكرا",   transliteration: "baʿd bukra",  english: "Day after tomorrow" },
      { arabic: "الأسبوع",    transliteration: "il-isbūʿ",    english: "The week" },
      { arabic: "الشهر",      transliteration: "ish-shahar",  english: "The month" },
      { arabic: "السنة",      transliteration: "is-sane",     english: "The year" },
      { arabic: "الفصل",      transliteration: "il-faṣl",     english: "The season" },
    ],
  },

  // ─── Plural Forms ─────────────────────────────────────────────────────────
  {
    id: "plurals",
    title: "Plural Forms",
    emoji: "🔢",
    description: "Singular → plural for time words and common nouns",
    color: "#7C3AED",
    rules: [
      "يوم → أيام (yōm → ayam): day → days",
      "جمعة → جمع (jem'a → jumaʿ): week → weeks",
      "شهر → أشهر / شهور (shahar → ash'hur / shuhūr): month → months",
      "سنة → سنين (sane → snīn): year → years",
      "فصل → فصول (faṣl → fuṣūl): season → seasons",
    ],
    items: [
      { arabic: "يوم",     transliteration: "yōm",      english: "Day (singular)" },
      { arabic: "أيام",    transliteration: "ayam",     english: "Days (plural)" },
      { arabic: "جمعة",    transliteration: "jem'a",    english: "Week (singular)" },
      { arabic: "جمع",     transliteration: "jumaʿ",   english: "Weeks (plural)" },
      { arabic: "شهر",     transliteration: "shahar",   english: "Month (singular)" },
      { arabic: "أشهر",    transliteration: "ash'hur",  english: "Months (plural, short)" },
      { arabic: "شهور",    transliteration: "shuhūr",   english: "Months (plural, long)" },
      { arabic: "سنة",     transliteration: "sane",     english: "Year (singular)" },
      { arabic: "سنين",    transliteration: "snīn",     english: "Years (plural)" },
      { arabic: "فصل",     transliteration: "faṣl",     english: "Season (singular)" },
      { arabic: "فصول",    transliteration: "fuṣūl",    english: "Seasons (plural)" },
      { arabic: "ساعة",    transliteration: "sāʿa",    english: "Hour / Watch (singular)" },
      { arabic: "ساعات",   transliteration: "sāʿāt",   english: "Hours (plural)" },
      { arabic: "دقيقة",   transliteration: "daqīqa",  english: "Minute (singular)" },
      { arabic: "دقائق",   transliteration: "daqāyeq", english: "Minutes (plural)" },
    ],
  },

  // ─── WH-Questions ─────────────────────────────────────────────────────────
  {
    id: "wh-questions",
    title: "WH-Questions",
    emoji: "❓",
    description: "How to ask questions in Palestinian dialect",
    color: "#D97706",
    rules: [
      "شو (shū) replaces ماذا — use it for 'what'",
      "وين (wēn) = where — used everywhere in Palestinian dialect",
      "أيمتى (aymata) = when — sometimes said إيمتى",
      "كيف (kīf) = how — same as MSA but without formal pronunciation",
      "قديش / أديش (addēsh / qaddēsh) = how much / how many",
      "ليش (lēsh) = why — uniquely Levantine, not used in Gulf Arabic",
    ],
    items: [
      { arabic: "شو",        transliteration: "shū",       english: "What?",              note: "شو بتبي؟ = What do you want?" },
      { arabic: "وين",       transliteration: "wēn",       english: "Where?",             note: "وين رايح؟ = Where are you going?" },
      { arabic: "أيمتى",     transliteration: "aymata",    english: "When?",              note: "أيمتى بترجع؟ = When are you coming back?" },
      { arabic: "كيف",       transliteration: "kīf",       english: "How?",               note: "كيف حالك؟ = How are you?" },
      { arabic: "ليش",       transliteration: "lēsh",      english: "Why?",               note: "ليش ما جيت؟ = Why didn't you come?" },
      { arabic: "أديش",      transliteration: "addēsh",    english: "How much / many?",   note: "أديش الحساب؟ = How much is the bill?" },
      { arabic: "مين",       transliteration: "mīn",       english: "Who?",               note: "مين هاد؟ = Who is this?" },
      { arabic: "أنو",       transliteration: "anū",       english: "Which?",             note: "أنو واحد؟ = Which one?" },
    ],
  },

  // ─── Connectors ───────────────────────────────────────────────────────────
  {
    id: "connectors",
    title: "Connectors",
    emoji: "🔗",
    description: "Prepositions and linking words — the glue of sentences",
    color: "#059669",
    rules: [
      "في (fī) = in/at — used for location and time",
      "من (min) = from — also means 'some of'",
      "على (ʿala) = on/about — also used for 'calling someone'",
      "بعدين (baʿdēn) = then/after — very commonly used in conversation",
      "لأنو (laʾanno) = because — Palestinian form of لأن",
    ],
    items: [
      { arabic: "في",        transliteration: "fī",        english: "In / At",            note: "في البيت = at home" },
      { arabic: "على",       transliteration: "ʿala",      english: "On / About",         note: "على التلفون = on the phone" },
      { arabic: "من",        transliteration: "min",       english: "From",               note: "من وين؟ = from where?" },
      { arabic: "لـ / لـ",   transliteration: "la-",       english: "To / For",           note: "رحت لعمان = I went to Amman" },
      { arabic: "مع",        transliteration: "maʿ",       english: "With",               note: "مع بعض = together" },
      { arabic: "بدون",      transliteration: "bidūn",     english: "Without" },
      { arabic: "لأنو",      transliteration: "laʾanno",   english: "Because",            note: "لأنو تعبان = because he's tired" },
      { arabic: "بس",        transliteration: "bas",       english: "But / Just / Only",  note: "بس شوي = just a little" },
      { arabic: "و",         transliteration: "w-",        english: "And",                note: "attached to next word: وبعدين" },
      { arabic: "أو",        transliteration: "aw",        english: "Or" },
      { arabic: "أول",       transliteration: "awwal",     english: "First",              note: "أول روح.. = first go..." },
      { arabic: "بعدين",     transliteration: "baʿdēn",   english: "Then / After",       note: "وبعدين رحنا = and then we went" },
      { arabic: "وأخيرًا",   transliteration: "w-akhīran", english: "And finally" },
      { arabic: "لما",       transliteration: "lamma",     english: "When (conjunction)", note: "لما وصل = when he arrived" },
      { arabic: "إذا",       transliteration: "iza",       english: "If",                 note: "إذا جيت = if you come" },
    ],
  },

  // ─── Telling Time — Range 1 ───────────────────────────────────────────────
  {
    id: "time-range-1",
    title: "Telling Time — Minutes",
    emoji: "⏰",
    description: "How to say the time from :00 to :29 (past the hour)",
    color: "#DC2626",
    rules: [
      "الساعة كم؟ (il-sāʿa kam?) = What time is it?",
      "Pattern for :00–:29 → 'الساعة [hour] وَ [minutes]'",
      "الساعة أربعة = 4:00 exactly",
      "الساعة أربعة وعشرة = 4:10",
      "الساعة أربعة وربع = 4:15 (ربع = quarter)",
      "الساعة أربعة ونص = 4:30 (نص = half)",
      "Numbers 1–10: واحد، اثنين، ثلاثة، أربعة، خمسة، ستة، سبعة، ثمانية، تسعة، عشرة",
    ],
    items: [
      { arabic: "الساعة كم؟",           transliteration: "il-sāʿa kam?",         english: "What time is it?" },
      { arabic: "الساعة أربعة",          transliteration: "il-sāʿa arbaʿa",       english: "4:00 (on the hour)" },
      { arabic: "الساعة أربعة وواحد",    transliteration: "il-sāʿa arbaʿa w-wāḥad", english: "4:01" },
      { arabic: "الساعة أربعة وعشرة",    transliteration: "il-sāʿa arbaʿa w-ʿashara", english: "4:10" },
      { arabic: "الساعة أربعة وربع",     transliteration: "il-sāʿa arbaʿa w-rubʿ", english: "4:15 (quarter past)" },
      { arabic: "الساعة أربعة وعشرين",   transliteration: "il-sāʿa arbaʿa w-ʿishrīn", english: "4:20" },
      { arabic: "الساعة أربعة ونص",      transliteration: "il-sāʿa arbaʿa w-nuṣṣ", english: "4:30 (half past)" },
      { arabic: "الساعة أربعة وتلت",     transliteration: "il-sāʿa arbaʿa w-tilt", english: "4:20 (⅓ of hour, alt.)" },
      { arabic: "الفجر / الصبح",         transliteration: "il-fajr / iṣ-ṣubḥ",   english: "Dawn / Morning", note: "AM time context" },
      { arabic: "الظهر",                  transliteration: "iẓ-ẓuhr",             english: "Noon", note: "12:00 PM" },
      { arabic: "العصر",                  transliteration: "il-ʿaṣr",             english: "Afternoon" },
      { arabic: "المغرب",                 transliteration: "il-maghrib",          english: "Sunset / Evening" },
      { arabic: "الليل",                  transliteration: "il-lēl",              english: "Night" },
    ],
  },

  // ─── Telling Time — Range 2 ───────────────────────────────────────────────
  {
    id: "time-range-2",
    title: "Telling Time — To the Hour",
    emoji: "⏱️",
    description: "How to say the time from :31 to :59 (before the next hour)",
    color: "#9333EA",
    rules: [
      "Pattern for :31–:59 → 'الساعة [NEXT hour] إلا [minutes remaining]'",
      "إلا (illa) = minus / except → counts DOWN to the next hour",
      "الساعة خمسة إلا ربع = 4:45 (5 minus a quarter)",
      "الساعة خمسة إلا عشرة = 4:50 (5 minus 10)",
      "الساعة خمسة إلا خمسة = 4:55 (5 minus 5)",
      "تمام (tamām) = exactly — الساعة خمسة تمام = exactly 5:00",
    ],
    items: [
      { arabic: "الساعة خمسة إلا ربع",    transliteration: "il-sāʿa khamse illa rubʿ",   english: "4:45 (quarter to 5)" },
      { arabic: "الساعة خمسة إلا عشرة",   transliteration: "il-sāʿa khamse illa ʿashara", english: "4:50 (ten to 5)" },
      { arabic: "الساعة خمسة إلا خمسة",   transliteration: "il-sāʿa khamse illa khamse", english: "4:55 (five to 5)" },
      { arabic: "الساعة خمسة تمام",        transliteration: "il-sāʿa khamse tamām",       english: "5:00 exactly" },
      { arabic: "تقريبًا",                  transliteration: "taqrīban",                   english: "Approximately / Around", note: "الساعة أربعة تقريبًا = around 4" },
      { arabic: "إلا",                      transliteration: "illa",                       english: "Minus / Less / Except", note: "used for counting down to hour" },
      { arabic: "تمام",                     transliteration: "tamām",                      english: "Exactly / On the dot" },
      { arabic: "وشوي",                     transliteration: "w-shwayy",                   english: "And a little / Just past", note: "الساعة أربعة وشوي = just after 4" },
    ],
  },

  // ─── Peace Corps Jordan Lessons ──────────────────────────────────────────

  {
    id: "greetings",
    title: "Greetings",
    emoji: "👋",
    description: "Essential greetings and introductions in Jordanian/Palestinian dialect",
    color: "#2563EB",
    rules: [
      "Reply to مرحبا with أهلين or هلا",
      "Reply to صباح الخير with صباح النور",
      "يعطيك العافية is said to someone working hard — reply with اللّه يعافيك",
    ],
    items: [
      { arabic: "السلام عليكم",   transliteration: "assalamu alaikum",    english: "Peace be upon you (greeting)" },
      { arabic: "عليكم السلام",   transliteration: "wa alaikum assalam",  english: "And peace be upon you (reply)" },
      { arabic: "مرحبا",          transliteration: "marHaba",             english: "Hello" },
      { arabic: "أهلين",          transliteration: "ahlain",              english: "Hello (reply)" },
      { arabic: "هلا",            transliteration: "hala",                english: "Hey / Hello (casual reply)" },
      { arabic: "صباح الخير",     transliteration: "SabaH elKhair",      english: "Good morning" },
      { arabic: "صباح النور",     transliteration: "SabaH ennoor",       english: "Good morning (reply — lit. morning of light)" },
      { arabic: "مع السلامة",     transliteration: "Ma'a asslamah",      english: "Goodbye (lit. go in safety)" },
      { arabic: "يعطيك العافية",  transliteration: "Ya'Tiik el'afya",    english: "May God give you strength (m)", note: "Said to someone working" },
      { arabic: "اللّه يعافيك",   transliteration: "Allah y'aafiik",     english: "May God give you strength — reply (m)" },
      { arabic: "شو إسمَك؟",     transliteration: "shuu ismak?",        english: "What is your name? (m)" },
      { arabic: "شو إسمِك؟",     transliteration: "shuu ismek?",        english: "What is your name? (f)" },
      { arabic: "أنا إسمي",      transliteration: "ana ismi",           english: "My name is..." },
    ],
  },

  {
    id: "how-are-you",
    title: "How Are You?",
    emoji: "🤝",
    description: "Asking and answering how someone is feeling",
    color: "#059669",
    rules: [
      "Most common reply to كيف حالك is الحمد لله",
      "Add -ة to make feminine: كويس → كويسة, تعبان → تعبانة",
      "تمام = perfect/OK — very common positive reply",
    ],
    items: [
      { arabic: "كيف حالَك؟",   transliteration: "kaif Halak?",    english: "How are you? (m)" },
      { arabic: "كيف حالِك؟",   transliteration: "kaif Halik?",    english: "How are you? (f)" },
      { arabic: "الحمد لله",    transliteration: "alHamdu lillah", english: "Thank God (most common reply)" },
      { arabic: "تمام",          transliteration: "tamam",           english: "OK / Perfect" },
      { arabic: "كويس",          transliteration: "kwayes",          english: "Good (m)" },
      { arabic: "كويسة",         transliteration: "kwayesa",         english: "Good (f)" },
      { arabic: "مبسوط",         transliteration: "mabSuuT",         english: "Happy (m)" },
      { arabic: "مبسوطة",        transliteration: "mabSuuTa",        english: "Happy (f)" },
      { arabic: "تعبان",         transliteration: "Ta'ban",          english: "Tired (m)" },
      { arabic: "تعبانة",        transliteration: "ta'bana",         english: "Tired (f)" },
    ],
  },

  {
    id: "family",
    title: "Family",
    emoji: "👨‍👩‍👧‍👦",
    description: "Family members and how to talk about your family",
    color: "#7C3AED",
    rules: [
      "أنا عندي = I have (lit. 'I have at me')",
      "عيلة = family in dialect (formal Arabic: عائلة)",
      "أبو = father — also used in kunya names like أبو محمد",
    ],
    items: [
      { arabic: "عيلة",       transliteration: "'aila",       english: "Family" },
      { arabic: "أبو",        transliteration: "abu",          english: "Father" },
      { arabic: "أم",         transliteration: "umm",          english: "Mother" },
      { arabic: "أخو",        transliteration: "aKhu",         english: "Brother" },
      { arabic: "أخت",        transliteration: "oKht",         english: "Sister" },
      { arabic: "إبن",        transliteration: "iben",         english: "Son" },
      { arabic: "بنت",        transliteration: "bent",         english: "Daughter" },
      { arabic: "زوج",        transliteration: "zawj",         english: "Husband" },
      { arabic: "زوجة",       transliteration: "zawja",        english: "Wife" },
      { arabic: "أنا عندي",  transliteration: "ana 'endi",   english: "I have...", note: "أنا عندي أخو = I have a brother" },
    ],
  },

  {
    id: "useful-expressions",
    title: "Useful Expressions",
    emoji: "💬",
    description: "Must-know everyday expressions for any situation",
    color: "#D97706",
    rules: [
      "عفواً = both 'excuse me' AND 'you're welcome'",
      "إن شاء الله is used constantly — can mean yes, maybe, or a polite no",
      "يللا is one of the most common words — means come on / let's go",
    ],
    items: [
      { arabic: "آسف",          transliteration: "aassef",       english: "Sorry (m)" },
      { arabic: "آسفة",         transliteration: "aassfah",      english: "Sorry (f)" },
      { arabic: "عفواً",        transliteration: "'afwan",       english: "Excuse me / You're welcome" },
      { arabic: "بسيطة",        transliteration: "basiiTa",      english: "It's OK / No big deal" },
      { arabic: "مش مشكلة",    transliteration: "mish mushkelah", english: "No problem!" },
      { arabic: "لو سمحت",     transliteration: "law samaHt",   english: "Please / Would you..." },
      { arabic: "شكراً",        transliteration: "shukran",      english: "Thank you" },
      { arabic: "تفضل",         transliteration: "tfaDDal",      english: "Here you go / Be my guest (m)" },
      { arabic: "تفضلي",        transliteration: "tfaDDalii",    english: "Here you go / Be my guest (f)" },
      { arabic: "إن شاء الله", transliteration: "inshalla",     english: "If God wills / Hopefully", note: "Can mean yes, maybe, or polite no" },
      { arabic: "يللا",         transliteration: "yallah",       english: "Come on! / Let's go!" },
      { arabic: "طيّب",         transliteration: "tayyeb",       english: "OK / I agree" },
      { arabic: "ماشي",         transliteration: "mashii",       english: "OK / Alright" },
      { arabic: "ممكن",         transliteration: "mumken",       english: "Possible / Can I...?" },
      { arabic: "هسا",          transliteration: "hassaa",       english: "Now" },
      { arabic: "بعدين",        transliteration: "ba'dain",      english: "Later" },
      { arabic: "عادي",         transliteration: "'aadii",       english: "Normal / No big deal" },
    ],
  },

  {
    id: "communication",
    title: "Communication Help",
    emoji: "🗣️",
    description: "What to say when you don't understand or need help communicating",
    color: "#DC2626",
    rules: [
      "مش = not in dialect (also: ما or لا depending on context)",
      "شويا شويا = slowly OR 'a little bit' — very versatile word",
      "Add مش before adjective to negate: فاهم → مش فاهم",
    ],
    items: [
      { arabic: "أنا مش فاهم",               transliteration: "ana mish faahem",              english: "I don't understand (m)" },
      { arabic: "أنا مش فاهمة",              transliteration: "ana mish faahema",             english: "I don't understand (f)" },
      { arabic: "أنا ما أعرف",              transliteration: "ana ma a'raf",                 english: "I don't know" },
      { arabic: "أنا ما أحب",               transliteration: "ana ma aHeb",                  english: "I don't like" },
      { arabic: "أنا ما بدي",               transliteration: "ana ma beddi",                 english: "I don't want" },
      { arabic: "كمان مرة",                  transliteration: "Kamaan marra",                 english: "Again / One more time" },
      { arabic: "مرة ثانية",                transliteration: "marra thanya",                 english: "Another time / Once more" },
      { arabic: "شويا شويا",                transliteration: "shwaya shwaya",                english: "Slowly! / Little by little" },
      { arabic: "أنا ما أحكي عربي كثير",   transliteration: "ana ma aHkii arabi kthiir",    english: "I can't speak much Arabic" },
    ],
  },

  {
    id: "food",
    title: "Food & Drink",
    emoji: "🍽️",
    description: "Food, drinks, meals, and hunger/fullness vocabulary",
    color: "#16A34A",
    rules: [
      "قهوة = gahwa (coffee) in rural areas, 'ahwa in Amman — the ق is dropped",
      "Add -ة for feminine state: جوعان → جوعانة, عطشان → عطشانة",
      "زاكي = delicious in dialect (formal: لذيذ)",
    ],
    items: [
      { arabic: "خبز",    transliteration: "Khubez",   english: "Bread" },
      { arabic: "جبنة",   transliteration: "jebna",    english: "Cheese" },
      { arabic: "رز",     transliteration: "ruz",      english: "Rice" },
      { arabic: "ملح",    transliteration: "mileH",    english: "Salt" },
      { arabic: "سكر",    transliteration: "sukkar",   english: "Sugar" },
      { arabic: "ميّ",    transliteration: "maii",     english: "Water" },
      { arabic: "شاي",    transliteration: "shaii",    english: "Tea" },
      { arabic: "قهوة",   transliteration: "gahwa",    english: "Coffee", note: "Pronounced 'ahwa in Amman" },
      { arabic: "حليب",   transliteration: "Haliib",   english: "Milk" },
      { arabic: "عصير",   transliteration: "'aSiir",   english: "Juice" },
      { arabic: "خضار",   transliteration: "KhuDar",   english: "Vegetables" },
      { arabic: "فواكه",  transliteration: "fawakeh",  english: "Fruit" },
      { arabic: "فطور",   transliteration: "fuTuur",   english: "Breakfast" },
      { arabic: "غدا",    transliteration: "Ghada",    english: "Lunch" },
      { arabic: "عشا",    transliteration: "'asha",    english: "Dinner" },
      { arabic: "زاكي",   transliteration: "zaaki",    english: "Delicious" },
      { arabic: "جوعان",  transliteration: "ju'aan",   english: "Hungry (m)" },
      { arabic: "عطشان",  transliteration: "'aTshaan", english: "Thirsty (m)" },
      { arabic: "شبعان",  transliteration: "shab'aan", english: "Full / Satisfied (m)" },
    ],
  },

  {
    id: "numbers",
    title: "Numbers & Money",
    emoji: "🔢",
    description: "Numbers 0-10 and money vocabulary for shopping",
    color: "#0891B2",
    rules: [
      "قديش؟ = How much? — use this for prices",
      "Numbers 3-10 take opposite gender agreement in Arabic",
      "مصاري = money in dialect (formal: مال or نقود)",
    ],
    items: [
      { arabic: "صفر",    transliteration: "Siffer",    english: "Zero" },
      { arabic: "واحد",   transliteration: "waHad",     english: "One" },
      { arabic: "اثنين",  transliteration: "ethnain",   english: "Two" },
      { arabic: "ثلاثة",  transliteration: "thalatha",  english: "Three" },
      { arabic: "اربعة",  transliteration: "arba'a",    english: "Four" },
      { arabic: "خمسة",   transliteration: "Khamsa",    english: "Five" },
      { arabic: "ستة",    transliteration: "sitta",     english: "Six" },
      { arabic: "سبعة",   transliteration: "sab'a",     english: "Seven" },
      { arabic: "ثمانية", transliteration: "thamania",  english: "Eight" },
      { arabic: "تسعة",   transliteration: "tes'a",     english: "Nine" },
      { arabic: "عشرة",   transliteration: "'ashara",   english: "Ten" },
      { arabic: "مصاري",  transliteration: "maSari",    english: "Money" },
      { arabic: "قرش",    transliteration: "gersh",     english: "Gersh (small coin)" },
      { arabic: "دينار",  transliteration: "diinar",    english: "Dinar" },
      { arabic: "قديش؟",  transliteration: "gaddaish?", english: "How much? / How many?" },
      { arabic: "الباقي", transliteration: "elbagii",   english: "The change (money back)" },
    ],
  },

  {
    id: "directions",
    title: "Directions & Places",
    emoji: "🗺️",
    description: "How to ask for and give directions in the dialect",
    color: "#9333EA",
    rules: [
      "وين؟ = Where? in dialect (formal Arabic: أين؟)",
      "دغري = straight ahead — one of the most common direction words",
      "شمال = left in dialect AND North in formal Arabic",
    ],
    items: [
      { arabic: "وين؟",         transliteration: "wain?",    english: "Where?", note: "Formal: أين؟" },
      { arabic: "شمال",          transliteration: "shmaal",   english: "Left", note: "Also means North in formal Arabic" },
      { arabic: "يسار",          transliteration: "yassaar",  english: "Left (formal)" },
      { arabic: "يمين",          transliteration: "yamiin",   english: "Right" },
      { arabic: "دغري",          transliteration: "duGhri",   english: "Straight ahead" },
      { arabic: "فوق",           transliteration: "faug",     english: "Up / Above" },
      { arabic: "تحت",           transliteration: "taHt",     english: "Down / Below / Under" },
      { arabic: "جنب",           transliteration: "janb",     english: "Next to / Beside" },
      { arabic: "في",            transliteration: "fii",      english: "In / At" },
      { arabic: "شارع",          transliteration: "share'",   english: "Street" },
      { arabic: "مكتب",          transliteration: "maktab",   english: "Office" },
      { arabic: "مكتب بريد",    transliteration: "maktab barid", english: "Post office" },
      { arabic: "هون",           transliteration: "haun",     english: "Here" },
      { arabic: "هناك",          transliteration: "hunaak",   english: "There" },
    ],
  },
];
